name: Auto release
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Release on npm version change
        uses: ScaleXY/ga01-release-action@master
        id: release
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        input:
          path: /home/runner/work/jp01-client/jp01-client/package.json
